application: mylesdgrant
version: 1
runtime: python
api_version: 1

default_expiration: "365d"

handlers:
- url: /css/(.*)\.v(\d+).css
  static_files: static/css/\1.css
  upload: static/css/(.*\.css)

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images

- url: /swfs
  static_dir: static/swfs
 
- url: /wp
  static_dir: static/wp

- url: /.well-known
  static_dir: static/.well-known

- url: /profiles
  static_dir: static/profiles

- url: /(.*\.txt)
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /google1603b937ca408129.html
  static_files: static/google1603b937ca408129.html
  upload: static/google1603b937ca408129.html

- url: /ydnzBHAop.html
  static_files: static/ydnzBHAop.html
  upload: static/ydnzBHAop.html

- url: /your_moms_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /admin/.*
  script: admin.py
  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: .*
  script: main.py

admin_console:
  pages:
  - name: Appstats
    url: /stats